# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brandgroup',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_began', models.BigIntegerField(blank=True, null=True)),
                ('year_ended', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'brandgroup',
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Indiciapublisher',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_began', models.BigIntegerField(blank=True, null=True)),
                ('year_ended', models.BigIntegerField(blank=True, null=True)),
                ('is_surrogate', models.NullBooleanField()),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'indiciapublisher',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('issue_number', models.BigIntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('page_count', models.BigIntegerField(blank=True, null=True)),
                ('indicia_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('editing', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
                ('valid_isbn', models.BigIntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('on_sale_date', models.DateField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Personandstudio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'personandstudio',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_began', models.BigIntegerField(blank=True, null=True)),
                ('year_ended', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('year_began', models.DateField(blank=True, null=True)),
                ('year_ended', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_stock', models.BigIntegerField(blank=True, null=True)),
                ('binding', models.CharField(blank=True, max_length=2000, null=True)),
                ('publishing_format', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('reprint_notes', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Appearsin',
            fields=[
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='interface.Characters')),
            ],
            options={
                'managed': False,
                'db_table': 'appearsin',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('person_and_studio', models.ForeignKey(db_column='person_and_studio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='interface.Personandstudio')),
            ],
            options={
                'managed': False,
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='interface.Characters')),
            ],
            options={
                'managed': False,
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Inks',
            fields=[
                ('person_and_studio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='interface.Personandstudio')),
            ],
            options={
                'managed': False,
                'db_table': 'inks',
            },
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('person_and_studio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='interface.Personandstudio')),
            ],
            options={
                'managed': False,
                'db_table': 'letters',
            },
        ),
        migrations.CreateModel(
            name='Pencils',
            fields=[
                ('person_and_studio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='interface.Personandstudio')),
            ],
            options={
                'managed': False,
                'db_table': 'pencils',
            },
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('person_and_studio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='interface.Personandstudio')),
            ],
            options={
                'managed': False,
                'db_table': 'scripts',
            },
        ),
    ]
